### ISSUE TITLE
ValueError: Keras Visualizer: Layer not supported for visualizing

### ISSUE THREAD

**Issue by StefanBloemheuvel** [lordmahyar/keras-visualizer#1]
Hi,

Thanks for creating this package, this could be of great help to me. 

However, I get the error that a layer is not supported for visualizing, and this error is not telling me which layer is the problem. My model uses Conv2D, Activation, GaussianDropout, MaxPool2D, Lambda, Concatenate, RepeatVector, Permute, tf.keras.backend.expand_dims, Flatten, Dense and also a layer where I multiple an activation layer with an weights_reshape. Do you plan to support any of these layers in the future? I think this would be of great help for visualizing layers in neural networks.

Kind regards!

Stefan

**Comment by knatheer** [comment]
Got the same error, even when I use the example posted on the git hub.
Is this due to backward compatibility?

Regards,
Natheer

**Comment by rmcrowley2000** [comment]
Same.  Even a simple network using just Input, Dense, and Dropout gets the same error.  Or a model with only a dense layer...  

And yeah, the documented examples don't work either.

**Comment by mahyar-amiri** [comment]
Hi, I apologize for the delay in replying. 

The package has been updated. In the new version, the library supports more layers. Some layers that are not supported are shown as general layers and also examples run correctly.

Thanks for your feedback.
