### ISSUE TITLE
Activation function name in output layer is printed wrong

### ISSUE THREAD

**Issue by yhpark-knu** [lordmahyar/keras-visualizer#2]
Thanks for the package keras-visulaizer.
As the plots in the examples 1 in the readme.md file, the name of the activation function is printed 'relu' in stead of 'sigmoid' activation.

**Comment by SledgeHammer01** [comment]
I am also seeing this issue.

**Comment by vkopey** [comment]
Please fix this error.

**Comment by mahyar-amiri** [comment]
Hi, I apologize for the delay in replying.

The `output layer's activation function name` bug has been fixed in the new version. 

Thanks for your feedback.
