### ISSUE TITLE
Feature Request: change max neurons per layer

### ISSUE THREAD

**Issue by swight-prc** [lordmahyar/keras-visualizer#3]
It looks as though there's a  maximum of 9 neurons displayed per Dense layer (at least - I haven't messed around too much with other layer types.) I would like to be able to update that per run, if that's possible.

Thanks!

**Comment by mahyar-amiri** [comment]
Hi, I apologize for the delay in replying.

The package has been updated. In the new version, you can simply change `MAX_NEURONS` for dense layer using code below.

```python
my_custom_settings = {
    'MAX_NEURONS': 16
}

visualizer(model, file_format='png', settings=my_custom_settings)
```
you can also see other settings in `README` [settings section](https://github.com/mahyar-amiri/keras-visualizer#settings).

Thanks for your feedback.
