### ISSUE TITLE
visualizing a multy columb architecture

### ISSUE THREAD

**Issue by fdsig** [lordmahyar/keras-visualizer#5]
This is an amazing resource!! just for starters- a step up from keras´s built in visualizer. viz_utils.
I can visualize your great examples just fine but am running into issues when trying to visualize a multi Columb CNN.

and getting the below error:

![Screenshot from 2021-06-10 21-53-46](https://user-images.githubusercontent.com/65113682/121595702-71218900-ca36-11eb-84c4-aef4073af859.png)

ValueError                                Traceback (most recent call last)

<ipython-input-10-bb0ab5975993> in <module>
      1 from keras_visualizer import visualizer
      2 
----> 3 visualizer(model, format='png', view=True)

v_enviroments/master/lib/python3.9/site-packages/keras_visualizer/__init__.py in visualizer(model, filename, format, view)
     49     for layer in model.layers:
     50         if layer == model.layers[0]:
---> 51             input_layer = int(str(layer.input_shape).split(',')[1][1:-1])
     52             hidden_layers_nr += 1
     53             if type(layer) == Dense:

ValueError: invalid literal for int() with base 10: ''

Thanks in advance!!
Frida

**Comment by mahyar-amiri** [comment]
Hi, I apologize for the delay in replying.

The bug has been fixed in the new version.

Thanks for your feedback.
