### ISSUE TITLE
Not supporting Multi Input keras layers

### ISSUE THREAD

**Issue by thomasjv799** [lordmahyar/keras-visualizer#6]
Ideally in the single input
model.layers[0].input_shape should give (None,X) where X is the input 

However in multi input 
model.layers[0].input_shape gives [(None,X)] which is causing "ValueError: invalid literal for int() with base 10:" because of extra ']' element.

Though I tried correcting this line finally its throwing a Exception

**Comment by emmarbee** [comment]
Have the same issue. Multi input layer works fine with keras.utils.plot_model though.

**Comment by mahyar-amiri** [comment]
Hi, I apologize for the delay in replying.

This issue is same as #5. The bug has been fixed in the new version.

Thanks for your feedback.
