### ISSUE TITLE
ValueError: [Keras Visualizer] Error while visualizing: <class 'Exception'>

### ISSUE THREAD

**Issue by chaowu2009** [lordmahyar/keras-visualizer#9]
using the following exampe as in the document:
  from keras import models, layers
  from keras_visualizer import visualizer
  
  model = models.Sequential([
      layers.Dense(64, activation='relu', input_shape=(8,)),
      layers.Dense(6, activation='softmax'),
      layers.Dense(32),
      layers.Dense(9, activation='sigmoid')
  ])
  
  visualizer(model, file_format='png', view=True)

and got the following error:

ValueError: [Keras Visualizer] Error while visualizing: <class 'Exception'>

windows environment with jupyter notebok.

**Comment by mahyar-amiri** [comment]
It seems that the problem is with the graphviz library. Try to install it by other methods or use Google Colab to run this code.
